language: python
python:
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then travis_retry pip install -r requirements36.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then travis_retry pip install -r requirements37.txt; fi
script:
  - pytest
